version: 2

#Data sources
sources:
  - name: sports_fan_behavior
    description: "Source Snowflake table with raw sports fan transactions."
    database: PC_DBT_DB
    schema: DBT_THANSEN
    tables:
      - name: SPORTS_FAN_BEHAVIOR
        description: "Raw sports fans dataset. Contains information about there sports interest, latest purchase in a given brand and amount"

  - name: brand_sponserships
    description: "Seed dataset containing brand sponsorship investment data."
    tables:
      - name: brand_sponserships
        description: >
          "brand_sponsorship containts information about different sponsorships by brands in a specific sport. It also includes the amount of money invested in the sponsorships"




#genetic test on staging data 
models:
  - name: stg_fan_behavior
    description: "Cleans and standardizes raw fan behavior data."
    columns:
      - name: fan_behavior_id
        description: "Unique identifier for each fan behavior record."
        tests: 
          - unique
          - not_null
      - name: spend
        description: "Amount spent by fans."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"
      - name: region
        description: "Geographical region."
        tests:
          - accepted_values:
              arguments:
                values: ['West', 'Midwest', 'Northeast', 'South']
      - name: brand
        tests:
          - not_null
      - name: category
        description: "High-level industry classification for the brand."
      - name: subcategory
        description: "More specific segment within the brand category."
 

 # Key uniqueness test 
  - name: dim_brand
    description: "Contains brand-level information and related sponsorship attributes."
    columns:
      - name: brand_key
        tests:
          - not_null
          - unique
      - name: category_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_category')
                field: category_key
  
  
  - name: dim_audience
    description: "Audience dimension."
    columns:
      - name: audience_key
        tests: 
          - unique
          - not_null


  - name: dim_region
    description: "Region dimension."
    columns:
      - name: region_key
        tests: 
          - unique 
          - not_null
  
  - name: dim_category
    columns:
      - name: category_key
        tests:
          - unique
          - not_null
      - name: category
        tests:
          - not_null
          - unique

  - name: dim_subcategory
    columns:
      - name: subcategory_key
        tests:
          - unique
          - not_null
      - name: subcategory
        tests:
          - not_null
      - name: category_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_category')
                field: category_key
  
  
  - name: dim_bridge_brand_subcategory
    columns:
      - name: brand_subcategory_key
        tests:
          - unique
          - not_null
      - name: brand_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_brand')
                field: brand_key
      - name: subcategory_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_subcategory')
                field: subcategory_key
  

  - name: dim_sponsorship
    description: "a dimension which hold information about sponsorship investments for different brands"
    columns:
      - name: sponsorship_key
        tests:
          - not_null
          - unique

          
          

  
  #Fact table with defined relationships to the different dimensions
  - name: fact_fan_spend
    description: "Fact table linking all fan spend transactions."
    columns:
      - name: fact_fan_spend_key
        tests: 
          - unique
          - not_null
      - name: brand_key
        tests:
          - relationships:
              arguments:
                to: ref('dim_brand')
                field: brand_key
      - name: audience_key
        tests:
          - relationships:
              arguments:
                to: ref('dim_audience')
                field: audience_key
      - name: region_key
        tests:
          - relationships:
              arguments:
                to: ref('dim_region')
                field: region_key
      - name: transaction_date
        tests:
          - not_null
