version: 2

#Data sources
sources:
  - name: sports_fan_behavior
    description: "Source Snowflake table with raw sports fan transactions."
    database: PC_DBT_DB
    schema: DBT_THANSEN
    tables:
      - name: SPORTS_FAN_BEHAVIOR
        description: "Raw sports fans dataset. Contains information about there sports interest, latest purchase in a given brand and amount"

  - name: brand_sponserships
    description: "Seed dataset containing brand sponsorship investment data."
    tables:
      - name: brand_sponserships
        description: >
          "brand_sponsorship containts information about different sponsorships by brands in a specific sport. It also includes the amount of money invested in the sponsorships"




#genetic test on values in the tables
models:
  - name: stg_fan_behavior
    description: "Cleans and standardizes raw fan behavior data."
    columns:
      - name: fan_behavior_id
        description: "Unique identifier for each fan behavior record."
        tests: 
          - unique
          - not_null
      - name: spend
        description: "Amount spent by fans."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"
      - name: percent_composition
        description: "Share of total spend (0–1)."
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0 AND percent_composition <= 1"
      - name: region
        description: "Geographical region."
        tests:
          - accepted_values:
              arguments:
                values: ['West', 'Midwest', 'Northeast', 'South']
 
  - name: dim_brand
    description: "Contains brand-level information and related sponsorship attributes."
    columns:
      - name: brand_key
        tests:
          - not_null
          - unique
      - name: brand
        tests:
          - not_null
      - name: category
        description: "High-level industry classification for the brand."
      - name: subcategory
        description: "More specific segment within the brand category."
  
  - name: dim_audience
    description: "Audience dimension."
    columns:
      - name: audience_key
        tests: 
          - unique
          - not_null

  - name: dim_region
    description: "Region dimension."
    columns:
      - name: region_key
        tests: 
          - unique 
          - not_null
        
      - name: region
        description: "Region name (e.g. West, Midwest, Northeast, South)."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['West', 'Midwest', 'Northeast', 'South']
  
  - name: dim_sponsorship
    description: "a dimension which hold information about sponsorship investments for different brands"
    columns:
      - name: sponsorship_key
        description: "unique surrogate key identifier for each sponsorship inevestment"
        tests:
          - not_null
          - unique

      - name: brand_key
        description: "foreign key that links sponsorship to dim_brand."
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_brand')
                field: brand_key

      - name: sponsorship_invest
        description: "Sponsorship spending in millions of USD. Can be null if not applicable."
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0 OR sponsorship_invest IS NULL"

          
          

  
  #Fact table with defined relationships to the different dimensions
  - name: fact_fan_spend
    description: "Fact table linking all fan spend transactions."
    columns:
      - name: fact_fan_spend_key
        tests: 
          - unique
          - not_null
      - name: brand_key
        tests:
          - relationships:
              arguments:
                to: ref('dim_brand')
                field: brand_key
      - name: audience_key
        tests:
          - relationships:
              arguments:
                to: ref('dim_audience')
                field: audience_key
      - name: region_key
        tests:
          - relationships:
              arguments:
                to: ref('dim_region')
                field: region_key

